tap "beeftornado/rmtree"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "cocoapods"
brew "coreutils"
brew "fzf"
brew "git"
brew "jq"
brew "mysql-client"
brew "openjdk"

cask "alt-tab"
cask "google-japanese-ime"
