tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "beeftornado/rmtree"
tap "nektos/tap"

brew "cocoapods"
brew "coreutils"
brew "fzf"
brew "git"
brew "jq"
brew "mysql-client"
brew "openjdk"
brew "nektos/tap/act"

cask "alt-tab"
cask "google-japanese-ime"
